# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7946283bbafd7af9765ab422ed1b88bbf8ad17a1f2faaafc04ea02075a4d09d22951454b6bbc873b25753ca0ff60b3b0715017ab53c6a884f5884c46988d2a43

test:
  secret_key_base: 58ac1b6e5caa584d1f3d71507b38d672b4f6e7109cd307e9e5ef5b34a2775c4806c4bd68bbbfdd78926a47b293c800697e1d6e05a0522f1ae0e51c75afc88b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
